# Generated by Django 5.1.1 on 2024-09-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="access",
            field=models.CharField(
                choices=[("any", "Anyone"), ("email_required", "Wmail required")],
                default="email_required",
                max_length=14,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="status",
            field=models.CharField(
                choices=[
                    ("pub", "Published"),
                    ("soon", "Coming Soon"),
                    ("draft", "Draft"),
                ],
                default="draft",
                max_length=10,
            ),
        ),
    ]
