# Generated by Django 5.1.1 on 2024-09-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_alter_course_access_alter_course_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="access",
            field=models.CharField(
                choices=[("any", "Anyone"), ("email", "Wmail required")],
                default="email",
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="status",
            field=models.CharField(
                choices=[
                    ("pub", "Published"),
                    ("soon", "Coming Soon"),
                    ("draft", "Draft"),
                ],
                default="draft",
                max_length=5,
            ),
        ),
    ]
