# Generated by Django 5.1.1 on 2024-09-27 08:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_alter_course_access_alter_course_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
