# Generated by Django 5.1.1 on 2024-09-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_alter_course_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="access",
            field=models.CharField(
                choices=[("any", "Anyone"), ("email", "Email required")],
                default="email",
                max_length=5,
            ),
        ),
    ]
